"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # <--- Asta e crucială

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-x+&u)bqe^wqo)ass3l16+^j-4o-yedylj-2soq%f_lx4iw7(@d")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

APP_DOMAIN = os.getenv("APP_DOMAIN", "http://127.0.0.1:8000")


# Application definition

INSTALLED_APPS = [
    "unfold",  # The modern admin theme
    "unfold.contrib.filters",  # Optional: Adds filter functionalities
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.bot",
    "apps.claims",  # <--- Trebuie să arate exact așa, cu 'apps.' în față
    "apps.signatures",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Calea fizică pe hard-disk unde se salvează fișierele
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# onfigurare Celery & Redis
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
# config/settings.py

# ... existing settings ...

# Twilio Configuration (Placeholders for development)
TWILIO_ACCOUNT_SID = "AC_PLACEHOLDER"
TWILIO_AUTH_TOKEN = "AUTH_PLACEHOLDER"
TWILIO_WHATSAPP_NUMBER = "whatsapp:+14155238886"  # Twilio Sandbox Number

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Auto Claims Admin",
    "SITE_HEADER": "Auto Claims Dashboard",
    "SITE_URL": "/",
    # "SITE_ICON": {
    #     "light": lambda request: static("icon.svg"),  # light mode
    #     "dark": lambda request: static("icon-dark.svg"),  # dark mode
    # },
    "DASHBOARD_CALLBACK": "apps.claims.dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "Principal",
                "separator": True,  # Top border
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": "admin:index",
                    },
                ],
            },
            {
                "title": "Dosare & Clienți",
                "separator": True,
                "items": [
                    {
                        "title": "Toate Dosarele",
                        "icon": "folder",
                        "link": "admin:claims_case_changelist",
                    },
                    {
                        "title": "Clienți",
                        "icon": "people",
                        "link": "admin:claims_client_changelist",
                    },
                    {
                        "title": "Documente la Dosar",
                        "icon": "description",
                        "link": "admin:claims_casedocument_changelist",
                    },
                ],
            },
            {
                "title": "Configurare",
                "separator": True,
                "items": [
                    {
                        "title": "Asiguratori",
                        "icon": "business",
                        "link": "admin:claims_insurer_changelist",
                    },
                    {
                        "title": "Vehicule Implicate",
                        "icon": "directions_car",
                        "link": "admin:claims_involvedvehicle_changelist",
                    },
                    {
                        "title": "Jurnal Conversații (Logs)",
                        "icon": "chat",
                        "link": "admin:claims_communicationlog_changelist",
                    },
                ],
            },
            {
                "title": "Utilizatori",
                "separator": True,
                "items": [
                    {
                        "title": "Utilizatori",
                        "icon": "person",
                        "link": "admin:auth_user_changelist",
                    },
                    {
                        "title": "Grupuri",
                        "icon": "group",
                        "link": "admin:auth_group_changelist",
                    },
                ],
            },
        ],
    },
}
