# Generated by Django 6.0.1 on 2026-01-10 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INIT', 'Inițiat (Discuție Start)'), ('UPLOAD', 'Așteptare Documente'), ('OCR', 'Procesare AI & OCR'), ('MISSING', 'Lipsesc Date (Manual)'), ('SIGN', 'Așteptare Semnătură'), ('READY', 'Pregătit de trimitere'), ('SENT', 'Trimis la Asigurator'), ('CLOSED', 'Închis')], default='INIT', max_length=10)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('is_signed_by_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='Format: +407...', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('doc_type', models.CharField(choices=[('CI', 'Buletin'), ('PERMIS', 'Permis'), ('TALON', 'Talon'), ('AMIABILA', 'Amiabilă'), ('PHOTO', 'Poză Daună'), ('POA_GEN', 'Procură (Nesemnată)'), ('POA_SIGNED', 'Procură (Semnată)'), ('UNK', 'Necunoscut')], default='UNK', max_length=15)),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='claims.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='claims.client'),
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Primit'), ('OUT', 'Trimis')], max_length=10)),
                ('channel', models.CharField(default='WHATSAPP', max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='claims.case')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VICTIM', 'Păgubit (Client)'), ('GUILTY', 'Vinovat'), ('UNKNOWN', 'Nedeterminat')], default='UNKNOWN', max_length=10)),
                ('license_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=30, null=True)),
                ('insurance_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_cnp', models.CharField(blank=True, max_length=13, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='claims.case')),
            ],
        ),
    ]
