# Generated by Django 6.0.1 on 2026-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='doc_type',
            field=models.CharField(choices=[('CI', 'Buletin'), ('PERMIS', 'Permis'), ('TALON', 'Talon'), ('AMIABILA', 'Amiabilă'), ('PHOTO', 'Poză Daună'), ('POA_GEN', 'Procură (Nesemnată)'), ('POA_SIGNED', 'Procură (Semnată)'), ('UNK', 'Necunoscut'), ('PROCURA', 'Procură')], default='UNK', max_length=15),
        ),
    ]
