# Generated by Django 6.0.1 on 2026-01-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_casedocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvedvehicle',
            name='is_offender',
            field=models.BooleanField(default=False, verbose_name='Este Vinovat?'),
        ),
    ]
