# Generated by Django 6.0.1 on 2026-01-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_involvedvehicle_is_offender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='is_signed_by_client',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='has_accident_report',
            field=models.BooleanField(default=False, verbose_name='Are Amiabilă/PV?'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_car_coupon',
            field=models.BooleanField(default=False, verbose_name='Are Talon?'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_id_card',
            field=models.BooleanField(default=False, verbose_name='Are Buletin?'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_mandate_signed',
            field=models.BooleanField(default=False, verbose_name='Mandat Semnat?'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_repair_auth',
            field=models.BooleanField(default=False, verbose_name='Are Aut. Reparație?'),
        ),
        migrations.AddField(
            model_name='case',
            name='has_scene_video',
            field=models.BooleanField(default=False, verbose_name='Are Video 360?'),
        ),
        migrations.AddField(
            model_name='case',
            name='insurer_claim_number',
            field=models.CharField(blank=True, help_text='Nr dosar la asigurator', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='insurer_email',
            field=models.EmailField(blank=True, help_text='Email identificat al asiguratorului', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='insurer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='is_human_managed',
            field=models.BooleanField(default=False, help_text='Dacă este True, botul NU mai răspunde automat. Se activează la Service RAR sau manual.'),
        ),
        migrations.AddField(
            model_name='case',
            name='resolution_choice',
            field=models.CharField(choices=[('REGIE', 'Regie Proprie'), ('SERVICE', 'Service Autorizat RAR'), ('DAUNA_TOTALA', 'Daună Totală'), ('N/A', 'Nedecis')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='settlement_offer_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ofertă (RON)'),
        ),
        migrations.AddField(
            model_name='case',
            name='stage',
            field=models.CharField(choices=[('GREETING', '1. Greeting / Alegere Flux'), ('DOCS', '2. Colectare Documente'), ('RES_SEL', '3. Alegere Tip Despăgubire'), ('SIGN', '4. Semnare Mandat'), ('INSURER', '5. Discuție Asigurator (Email)'), ('OFFER', '6. Decizie Ofertă Client'), ('CLOSED', '7. Dosar Închis')], default='GREETING', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='iban',
            field=models.CharField(blank=True, help_text='Pentru Regie Proprie', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='doc_type',
            field=models.CharField(choices=[('CI', 'Buletin'), ('PERMIS', 'Permis'), ('TALON', 'Talon'), ('AMIABILA', 'Amiabilă / PV Poliție'), ('AUT_REP', 'Autorizație Reparație'), ('PHOTO', 'Poză Daună / Video'), ('EXTRAS', 'Extras Cont'), ('ALTELE', 'Alte Documente'), ('MANDAT_RAW', 'Mandat (Generat)'), ('MANDAT_SIGN', 'Mandat (Semnat)'), ('CERERE', 'Cerere Despăgubire'), ('UNK', 'Necunoscut')], default='UNK', max_length=20),
        ),
    ]
