# Generated by Django 6.0.1 on 2026-01-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_remove_case_is_signed_by_client_remove_case_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nume Asigurator"),
                ),
                (
                    "email_claims",
                    models.EmailField(
                        help_text="Adresa unde se trimit documentele",
                        max_length=254,
                        verbose_name="Email Avizări Daune",
                    ),
                ),
                (
                    "identifiers",
                    models.CharField(
                        help_text="Cuvinte separate prin virgulă pentru identificare. Ex: 'groupama, grupama, group'",
                        max_length=255,
                        verbose_name="Cuvinte Cheie (Matching)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asigurator",
                "verbose_name_plural": "Listă Asiguratori",
            },
        ),
        migrations.AddField(
            model_name="case",
            name="has_bank_statement",
            field=models.BooleanField(default=False, verbose_name="Are Extras Cont?"),
        ),
        migrations.AddField(
            model_name="case",
            name="has_guilty_docs",
            field=models.BooleanField(default=False, verbose_name="Are Acte Vinovat?"),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("CI", "Buletin"),
                    ("PERMIS", "Permis"),
                    ("TALON", "Talon"),
                    ("AMIABILA", "Amiabilă / PV Poliție"),
                    ("AUT_REP", "Autorizație Reparație"),
                    ("PHOTO", "Poză Daună / Video"),
                    ("EXTRAS", "Extras Cont"),
                    ("VINV", "Acte Vinovat"),
                    ("ALTELE", "Alte Documente"),
                    ("MANDAT_RAW", "Mandat (Generat)"),
                    ("MANDAT_SIGN", "Mandat (Semnat)"),
                    ("CERERE", "Cerere Despăgubire"),
                    ("UNK", "Necunoscut"),
                ],
                default="UNK",
                max_length=20,
            ),
        ),
    ]
