# Generated by Django 6.0.1 on 2026-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "claims",
            "0005_insurer_case_has_bank_statement_case_has_guilty_docs_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="last_email_message_id",
            field=models.CharField(
                blank=True,
                help_text="Message-ID pentru threading email",
                max_length=255,
                null=True,
            ),
        ),
    ]
