# Generated by Django 6.0.1 on 2026-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_case_last_email_message_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="full_name",
        ),
        migrations.AddField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
