# Generated by Django 6.0.1 on 2026-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0007_remove_client_full_name_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="accident_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Eveniment"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Adresă Domiciliu"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Număr CI"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="id_series",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Serie CI"
            ),
        ),
        migrations.AddField(
            model_name="involvedvehicle",
            name="make",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Marca Auto"
            ),
        ),
        migrations.AddField(
            model_name="involvedvehicle",
            name="model",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Model Auto"
            ),
        ),
    ]
