# Generated by Django 6.0.1 on 2026-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0008_case_accident_date_client_address_client_id_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="has_car_identity",
            field=models.BooleanField(default=False, verbose_name="Are CIV?"),
        ),
        migrations.AddField(
            model_name="case",
            name="has_victim_rca",
            field=models.BooleanField(default=False, verbose_name="Are RCA Păgubit?"),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("CI", "Buletin"),
                    ("PERMIS", "Permis"),
                    ("TALON", "Talon"),
                    ("CIV", "Carte Identitate Vehicul"),
                    ("RCA", "RCA Păgubit"),
                    ("AMIABILA", "Amiabilă / PV Poliție"),
                    ("AUT_REP", "Autorizație Reparație"),
                    ("PHOTO", "Poză Daună / Video"),
                    ("EXTRAS", "Extras Cont"),
                    ("VINV", "Acte Vinovat"),
                    ("ALTELE", "Alte Documente"),
                    ("MANDAT_RAW", "Mandat (Generat)"),
                    ("MANDAT_SIGN", "Mandat (Semnat)"),
                    ("CERERE", "Cerere Despăgubire"),
                    ("UNK", "Necunoscut"),
                ],
                default="UNK",
                max_length=20,
            ),
        ),
    ]
