# Generated by Django 6.0.1 on 2026-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0009_case_has_car_identity_case_has_victim_rca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="involvedvehicle",
            name="policy_expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Expirare RCA"
            ),
        ),
    ]
