# Generated by Django 6.0.1 on 2026-03-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0010_involvedvehicle_policy_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="stage",
            field=models.CharField(
                choices=[
                    ("GREETING", "1. Greeting / Alegere Flux"),
                    ("DOCS", "2. Colectare Documente"),
                    ("GUILTY_INS", "2.5 Alegere Asigurator Vinovat"),
                    ("RES_SEL", "3. Alegere Tip Despăgubire"),
                    ("SIGN", "4. Semnare Mandat"),
                    ("INSURER", "5. Discuție Asigurator (Email)"),
                    ("OFFER", "6. Decizie Ofertă Client"),
                    ("CLOSED", "7. Dosar Închis"),
                ],
                default="GREETING",
                max_length=20,
            ),
        ),
    ]
