# Generated by Django 6.0.1 on 2026-04-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0011_alter_case_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="last_message_from_insurer_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="last_message_to_insurer_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
